---
title: "Untitled"
output: html_document
date: "2024-06-10"
---

```{r MDW}

df = read.csv('/home/jcrayb/Documents/GitHub/transport-research-project/analysis/MDW.csv')

linmod1 <- lm(rdiff ~ race + distance, data=df)
linmod2 <- lm(n_cameras ~ race + distance, data=df)
summary(linmod1)
summary(linmod2)
```

```{r hospital}

df = read.csv('/home/jcrayb/Documents/GitHub/transport-research-project/analysis/hospital.csv')
linmod1 <- lm(rdiff ~ race + distance, data=df)
linmod2 <- lm(n_cameras ~ race + distance, data=df)
summary(linmod1)
summary(linmod2)


```

```{r ORD}

df = read.csv('/home/jcrayb/Documents/GitHub/transport-research-project/analysis/ORD.csv')
linmod1 <- lm(rdiff ~ race + distance, data=df)
linmod2 <- lm(n_cameras ~ race + distance, data=df)
summary(linmod1)
summary(linmod2)
```
```{r CHI}

df = read.csv('/home/jcrayb/Documents/GitHub/transport-research-project/analysis/CHI.csv')
linmod1 <- lm(rdiff ~ race + distance, data=df)
linmod2 <- lm(n_cameras ~ race + distance, data=df)
summary(linmod1)
summary(linmod2)
```

