---
title: "Analysis"
output: latex_document
date: "2024-10-10"
---

```{r imports}
library(ggplot2)
```

## Union station

```{r data_chi}
data <- read.csv('./hospital-1-closest.csv')

#data$majority <-relevel(data$majority, ref='white')

head(data)
```

```{r means_chi}
black_mean <- mean(data[data$majority == 'black', ]$shortest_path)
white_mean <- mean(data[data$majority == 'white', ]$shortest_path)
```

### Mean time to reach by demographic group
```{r plot_means_chi}
ggplot(data, aes(x = seq_along(shortest_path), y = shortest_path, color = majority)) + geom_point() + geom_hline(yintercept=black_mean, size=1, color="#F8766D") + geom_hline(yintercept=white_mean, size=1, color="#00bfc4")
  labs(x = "Row Number", y = "Shortest Path", title = "Scatterplot with Group Average Line")
```

### Number of cameras on route by demographic group
```{r lm_chi}
linmod <- lm(data = data, n_cameras ~ majority + shortest_path)
summary(linmod)

linmod <- lm(data = data, absolute_increase ~ majority + shortest_path)
summary(linmod)
```

## Midway airport

```{r data}
data <- read.csv('./MDW.csv')

head(data)
```

```{r df}
black_mean <- mean(data[data$majority == 'black', ]$shortest_path)
white_mean <- mean(data[data$majority == 'white', ]$shortest_path)
```

```{r plot}
ggplot(data, aes(x = seq_along(shortest_path), y = shortest_path, color = majority)) + geom_point() + geom_hline(yintercept=black_mean, size=1, color="#F8766D") + geom_hline(yintercept=white_mean, size=1, color="#00bfc4")
  labs(x = "Row Number", y = "Shortest Path", title = "Scatterplot with Group Average Line")
```